package cliente;

import br.com.mackenzie.fci.si.pi2.cr.business.PassagemFacadeRemote;
import br.com.mackenzie.fci.si.pi2.cr.entity.Passagem;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ivan
 */
public class TelaListaCompras extends javax.swing.JPanel {

    private PassagemFacadeRemote passagemFacadeRemote = ServiceLocator.getPassageFacade();

    private List<Passagem> passagens = new ArrayList<Passagem>();
    
    public TelaListaCompras(String cpf) {
        initComponents();
        limparTabela();

        List<Passagem> passagens = passagemFacadeRemote.listarPassagensPorCPF(cpf);
        if (passagens.size() == 0) {
            JOptionPane.showMessageDialog(this, "Não foi encontrado nenhuma passagem para o CPF " + cpf);
            setVisible(false);
            return;
        }
        int numeroPassagens = passagens.size();
        String[] colunas = new String[]{"ID", "Nome", "Documento", "Viagem"};
        DefaultTableModel model = new DefaultTableModel(colunas, 0);
        for (Passagem passagem : passagens) {
            Object[] linha = new Object[]{passagem.getId(), passagem.getNomePassageiro(), passagem.getDocumentoPassageiro(), passagem.getViagem().getDescricao()};
            model.addRow(linha);
            this.passagens.add(passagem);
        }
        jTable2.setModel(model);
        setVisible(true);
    }

    private void limparTabela() {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        for (int i = 0; i < jTable2.getRowCount(); i++) {
            model.removeRow(i);
        }
        model.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Compras"));
        setToolTipText("");
        setName("");

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Viagem", "Linha", "Horário", "Valor", "Retirada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 212, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jTable2.getSelectedRow();
        if(selectedRow == -1) {
            return;
        }
        Passagem passagem = passagens.get(selectedRow);
        String viagem = jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0).toString();
        setVisible(false);
        String numeroAssento = passagem.getNumeroAssento() + "";
        String linha = passagem.getViagem().getLinha().getNome();
        String origem = passagem.getViagem().getOrigem().getNome() + "/" + passagem.getViagem().getOrigem().getEstado();
        String destino  = passagem.getViagem().getDestino().getNome() + "/" + passagem.getViagem().getDestino().getEstado();
        String data = new SimpleDateFormat("dd/MM/yyyy").format(passagem.getViagem().getData());
        String horario = new SimpleDateFormat("HH:mm").format(passagem.getViagem().getData());
        String nomePassageiro = passagem.getNomePassageiro();
        String documentoPassageiro = passagem.getDocumentoPassageiro();
        String valor = passagem.getViagem().getValor() + "";
        
        new TelaVisualizacaoDados(numeroAssento, linha, origem, destino, data, horario, nomePassageiro, documentoPassageiro, valor);
    }//GEN-LAST:event_jButton2ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
