package cliente;

import br.com.mackenzie.fci.si.pi2.cr.business.CidadeFacadeRemote;
import br.com.mackenzie.fci.si.pi2.cr.business.PassagemFacadeRemote;
import br.com.mackenzie.fci.si.pi2.cr.business.ViagemFacadeRemote;
import br.com.mackenzie.fci.si.pi2.cr.entity.Cidade;
import br.com.mackenzie.fci.si.pi2.cr.entity.Passagem;
import br.com.mackenzie.fci.si.pi2.cr.entity.Viagem;
import com.toedter.calendar.JCalendar;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this template, choose Tools | Templates and open the template in
 * the editor.
 */
public class TelaCompra extends javax.swing.JFrame {

    DateFormat format = new SimpleDateFormat("dd/MM/yyyy");
    final JCalendar calendario = new JCalendar();
    private CidadeFacadeRemote cidadeFacadeRemote = ServiceLocator.getCidadeFacade();
    private ViagemFacadeRemote viagemFacadeRemote = ServiceLocator.getViagemFacade();
    private PassagemFacadeRemote passagemFacadeRemote = ServiceLocator.getPassageFacade();
    private Map<String, Cidade> cidadeMap = new HashMap<String, Cidade>();
    private List<Long> viagensTable = new ArrayList<Long>();

    /**
     * Creates new form TelaCompra
     */
    public TelaCompra() {
        initComponents();

        cbDestino.removeAllItems();
        cbOrigem.removeAllItems();
        List<Cidade> cidades = cidadeFacadeRemote.findAll();
        for (Cidade cidade : cidades) {
            String nomeCidade = cidade.getNome() + "/" + cidade.getEstado();
            cbDestino.addItem(nomeCidade);
            cbOrigem.addItem(nomeCidade);
            cidadeMap.put(nomeCidade, cidade);
        }

        painelData.add(calendario);
        pack();
        setBounds(0, 0, 700, 550);
        setVisible(true);
        limparTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbInfo = new javax.swing.JTable();
        btnOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnProcurar = new javax.swing.JButton();
        painelData = new javax.swing.JPanel();
        cbOrigem = new javax.swing.JComboBox();
        cbDestino = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu btnArquivo = new javax.swing.JMenu();
        btnLogin = new javax.swing.JRadioButtonMenuItem();
        btnSair = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(null);

        tbInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Viagem", "Linha", "Horário", "Poltronas Disponíveis", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbInfo.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbInfo);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(20, 290, 630, 140);

        btnOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK);
        btnOK.setBounds(580, 440, 70, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Data:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(300, 50, 34, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Origem:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(18, 49, 49, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Destino:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 90, 56, 30);

        btnProcurar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnProcurar.setText("Procurar");
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        jPanel1.add(btnProcurar);
        btnProcurar.setBounds(150, 140, 110, 30);

        javax.swing.GroupLayout painelDataLayout = new javax.swing.GroupLayout(painelData);
        painelData.setLayout(painelDataLayout);
        painelDataLayout.setHorizontalGroup(
            painelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 286, Short.MAX_VALUE)
        );
        painelDataLayout.setVerticalGroup(
            painelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel1.add(painelData);
        painelData.setBounds(360, 50, 286, 210);

        cbOrigem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbOrigem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOrigemActionPerformed(evt);
            }
        });
        jPanel1.add(cbOrigem);
        cbOrigem.setBounds(80, 50, 180, 30);

        cbDestino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbDestino);
        cbDestino.setBounds(80, 90, 180, 30);

        getContentPane().add(jPanel1);

        btnArquivo.setText("Administrator");

        btnLogin.setSelected(true);
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnArquivo.add(btnLogin);

        btnSair.setSelected(true);
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        btnArquivo.add(btnSair);

        jMenuBar1.add(btnArquivo);

        jMenu3.setText("Compras");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Comprar Passagem");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Retirar Passagem");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sobre");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Integrantes");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        final int selectedRow = tbInfo.getSelectedRow();
        if(selectedRow == -1) {
            return;
        }
        Long viagemId = viagensTable.get(selectedRow);
        Viagem viagem = viagemFacadeRemote.find(viagemId);
        setVisible(false);
        new TelaEscolhaAssento(viagem);
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
   }//GEN-LAST:event_jComboBox2ActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        Cidade cidade1 = cidadeMap.get(cbOrigem.getSelectedItem().toString());
        Cidade cidade2 = cidadeMap.get(cbDestino.getSelectedItem().toString());
        Date data = calendario.getDate();
        final Long idOrigem = cidade1.getId();
        final Long idDestino = cidade2.getId();
        final String dataFormatada = new SimpleDateFormat("dd/MM/yyyy").format(data);
        List<Viagem> viagens = viagemFacadeRemote.listarViagens(idOrigem, idDestino, dataFormatada);

        if (viagens.size() == 0) {
            JOptionPane.showMessageDialog(this, "Não foram encontradas viagens", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        limparTabela();
        DefaultTableModel model = (DefaultTableModel) tbInfo.getModel();

        int count = 0;
        for (Viagem viagem : viagens) {
            List<Passagem> passagens = passagemFacadeRemote.listarPassagensCompradasPorViagem(viagem);
            model.addRow(new Object[]{
                        viagem.getDescricao(),
                        viagem.getLinha().getNome(),
                        viagem.getDataHoraFormatada(),
                        (viagem.getCarro().getAssentos() - passagens.size()),
                        "R$ " + viagem.getValor()
                    });
            viagensTable.add(viagem.getId());
            count++;
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void limparTabela() {
        DefaultTableModel model = (DefaultTableModel) tbInfo.getModel();
        for (int i = 0; i < tbInfo.getRowCount(); i++) {
            model.removeRow(i);
        }
        model.setRowCount(0);
        
        viagensTable.clear();
    }

    private void cbOrigemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOrigemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOrigemActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        TelaInicial inicial = new TelaInicial();
        inicial.setLocationRelativeTo(null);
        inicial.setVisible(true);

        frmMenu tamanho = new frmMenu();
        tamanho.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        TelaCompra compra = new TelaCompra();
        compra.setLocationRelativeTo(null);
        compra.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        TelaRetiraPassagem retira = new TelaRetiraPassagem();
        retira.setLocationRelativeTo(null);
        retira.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        Integrantes integrantes = new Integrantes();
        integrantes.setLocationRelativeTo(null);
        integrantes.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
   }//GEN-LAST:event_jMenu4ActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new TelaCompra();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem btnLogin;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JRadioButtonMenuItem btnSair;
    private javax.swing.JComboBox cbDestino;
    private javax.swing.JComboBox cbOrigem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel painelData;
    private javax.swing.JTable tbInfo;
    // End of variables declaration//GEN-END:variables
}
