package cliente;

import java.util.ArrayList;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TelaConfirmacao.java
 *
 * Created on 07/05/2012, 21:46:04
 */
/**
 *
 * @author 40901130
 */
public class TelaConfirmacao extends javax.swing.JFrame {
    
    /** Creates new form TelaConfirmacao */
    public TelaConfirmacao() {
        initComponents();
        setVisible(true);
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblOrigem = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        lblRota = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        poltrona2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        poltrona1 = new javax.swing.JPanel();
        poltrona4 = new javax.swing.JPanel();
        poltrona3 = new javax.swing.JPanel();
        poltrona5 = new javax.swing.JPanel();
        poltrona6 = new javax.swing.JPanel();
        poltrona7 = new javax.swing.JPanel();
        poltrona8 = new javax.swing.JPanel();
        poltrona9 = new javax.swing.JPanel();
        poltrona10 = new javax.swing.JPanel();
        poltrona11 = new javax.swing.JPanel();
        poltrona12 = new javax.swing.JPanel();
        poltrona13 = new javax.swing.JPanel();
        poltrona14 = new javax.swing.JPanel();
        poltrona15 = new javax.swing.JPanel();
        poltrona16 = new javax.swing.JPanel();
        poltrona17 = new javax.swing.JPanel();
        poltrona18 = new javax.swing.JPanel();
        poltrona19 = new javax.swing.JPanel();
        poltrona20 = new javax.swing.JPanel();
        poltrona21 = new javax.swing.JPanel();
        poltrona22 = new javax.swing.JPanel();
        poltrona25 = new javax.swing.JPanel();
        poltrona26 = new javax.swing.JPanel();
        poltrona29 = new javax.swing.JPanel();
        poltrona30 = new javax.swing.JPanel();
        poltrona33 = new javax.swing.JPanel();
        poltrona34 = new javax.swing.JPanel();
        poltrona37 = new javax.swing.JPanel();
        poltrona38 = new javax.swing.JPanel();
        poltrona39 = new javax.swing.JPanel();
        poltrona35 = new javax.swing.JPanel();
        poltrona31 = new javax.swing.JPanel();
        poltrona27 = new javax.swing.JPanel();
        poltrona23 = new javax.swing.JPanel();
        poltrona24 = new javax.swing.JPanel();
        poltrona28 = new javax.swing.JPanel();
        poltrona32 = new javax.swing.JPanel();
        poltrona36 = new javax.swing.JPanel();
        poltrona40 = new javax.swing.JPanel();
        poltrona41 = new javax.swing.JPanel();
        poltrona42 = new javax.swing.JPanel();
        poltrona45 = new javax.swing.JPanel();
        poltrona46 = new javax.swing.JPanel();
        poltrona43 = new javax.swing.JPanel();
        poltrona44 = new javax.swing.JPanel();
        poltrona47 = new javax.swing.JPanel();
        poltrona48 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        javax.swing.JMenu btnArquivo = new javax.swing.JMenu();
        btnLogin = new javax.swing.JRadioButtonMenuItem();
        btnSair = new javax.swing.JRadioButtonMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Confirmação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Horário:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Data:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Rota:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Destino:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Origem:");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        jPanel1.setToolTipText("Corredor");
        jPanel1.setLayout(null);

        poltrona2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona2Layout = new javax.swing.GroupLayout(poltrona2);
        poltrona2.setLayout(poltrona2Layout);
        poltrona2Layout.setHorizontalGroup(
            poltrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona2Layout.setVerticalGroup(
            poltrona2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona2);
        poltrona2.setBounds(60, 20, 30, 20);

        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(112, -5, 19, 390);

        poltrona1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona1Layout = new javax.swing.GroupLayout(poltrona1);
        poltrona1.setLayout(poltrona1Layout);
        poltrona1Layout.setHorizontalGroup(
            poltrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona1Layout.setVerticalGroup(
            poltrona1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona1);
        poltrona1.setBounds(20, 20, 30, 20);

        poltrona4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona4Layout = new javax.swing.GroupLayout(poltrona4);
        poltrona4.setLayout(poltrona4Layout);
        poltrona4Layout.setHorizontalGroup(
            poltrona4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona4Layout.setVerticalGroup(
            poltrona4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona4);
        poltrona4.setBounds(190, 20, 30, 20);

        poltrona3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona3Layout = new javax.swing.GroupLayout(poltrona3);
        poltrona3.setLayout(poltrona3Layout);
        poltrona3Layout.setHorizontalGroup(
            poltrona3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona3Layout.setVerticalGroup(
            poltrona3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona3);
        poltrona3.setBounds(150, 20, 30, 20);

        poltrona5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona5Layout = new javax.swing.GroupLayout(poltrona5);
        poltrona5.setLayout(poltrona5Layout);
        poltrona5Layout.setHorizontalGroup(
            poltrona5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona5Layout.setVerticalGroup(
            poltrona5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona5);
        poltrona5.setBounds(20, 50, 30, 20);

        poltrona6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona6Layout = new javax.swing.GroupLayout(poltrona6);
        poltrona6.setLayout(poltrona6Layout);
        poltrona6Layout.setHorizontalGroup(
            poltrona6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona6Layout.setVerticalGroup(
            poltrona6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona6);
        poltrona6.setBounds(60, 50, 30, 20);

        poltrona7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona7Layout = new javax.swing.GroupLayout(poltrona7);
        poltrona7.setLayout(poltrona7Layout);
        poltrona7Layout.setHorizontalGroup(
            poltrona7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona7Layout.setVerticalGroup(
            poltrona7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona7);
        poltrona7.setBounds(150, 50, 30, 20);

        poltrona8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona8Layout = new javax.swing.GroupLayout(poltrona8);
        poltrona8.setLayout(poltrona8Layout);
        poltrona8Layout.setHorizontalGroup(
            poltrona8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona8Layout.setVerticalGroup(
            poltrona8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona8);
        poltrona8.setBounds(190, 50, 30, 20);

        poltrona9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona9Layout = new javax.swing.GroupLayout(poltrona9);
        poltrona9.setLayout(poltrona9Layout);
        poltrona9Layout.setHorizontalGroup(
            poltrona9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona9Layout.setVerticalGroup(
            poltrona9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona9);
        poltrona9.setBounds(20, 80, 30, 20);

        poltrona10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona10Layout = new javax.swing.GroupLayout(poltrona10);
        poltrona10.setLayout(poltrona10Layout);
        poltrona10Layout.setHorizontalGroup(
            poltrona10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona10Layout.setVerticalGroup(
            poltrona10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona10);
        poltrona10.setBounds(60, 80, 30, 20);

        poltrona11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona11Layout = new javax.swing.GroupLayout(poltrona11);
        poltrona11.setLayout(poltrona11Layout);
        poltrona11Layout.setHorizontalGroup(
            poltrona11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona11Layout.setVerticalGroup(
            poltrona11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona11);
        poltrona11.setBounds(150, 80, 30, 20);

        poltrona12.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona12Layout = new javax.swing.GroupLayout(poltrona12);
        poltrona12.setLayout(poltrona12Layout);
        poltrona12Layout.setHorizontalGroup(
            poltrona12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona12Layout.setVerticalGroup(
            poltrona12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona12);
        poltrona12.setBounds(190, 80, 30, 20);

        poltrona13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona13Layout = new javax.swing.GroupLayout(poltrona13);
        poltrona13.setLayout(poltrona13Layout);
        poltrona13Layout.setHorizontalGroup(
            poltrona13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona13Layout.setVerticalGroup(
            poltrona13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona13);
        poltrona13.setBounds(20, 110, 30, 20);

        poltrona14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona14Layout = new javax.swing.GroupLayout(poltrona14);
        poltrona14.setLayout(poltrona14Layout);
        poltrona14Layout.setHorizontalGroup(
            poltrona14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona14Layout.setVerticalGroup(
            poltrona14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona14);
        poltrona14.setBounds(60, 110, 30, 20);

        poltrona15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona15Layout = new javax.swing.GroupLayout(poltrona15);
        poltrona15.setLayout(poltrona15Layout);
        poltrona15Layout.setHorizontalGroup(
            poltrona15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona15Layout.setVerticalGroup(
            poltrona15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona15);
        poltrona15.setBounds(150, 110, 30, 20);

        poltrona16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona16Layout = new javax.swing.GroupLayout(poltrona16);
        poltrona16.setLayout(poltrona16Layout);
        poltrona16Layout.setHorizontalGroup(
            poltrona16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona16Layout.setVerticalGroup(
            poltrona16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona16);
        poltrona16.setBounds(190, 110, 30, 20);

        poltrona17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona17Layout = new javax.swing.GroupLayout(poltrona17);
        poltrona17.setLayout(poltrona17Layout);
        poltrona17Layout.setHorizontalGroup(
            poltrona17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona17Layout.setVerticalGroup(
            poltrona17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona17);
        poltrona17.setBounds(20, 140, 30, 20);

        poltrona18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona18Layout = new javax.swing.GroupLayout(poltrona18);
        poltrona18.setLayout(poltrona18Layout);
        poltrona18Layout.setHorizontalGroup(
            poltrona18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona18Layout.setVerticalGroup(
            poltrona18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona18);
        poltrona18.setBounds(60, 140, 30, 20);

        poltrona19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona19Layout = new javax.swing.GroupLayout(poltrona19);
        poltrona19.setLayout(poltrona19Layout);
        poltrona19Layout.setHorizontalGroup(
            poltrona19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona19Layout.setVerticalGroup(
            poltrona19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona19);
        poltrona19.setBounds(150, 140, 30, 20);

        poltrona20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona20Layout = new javax.swing.GroupLayout(poltrona20);
        poltrona20.setLayout(poltrona20Layout);
        poltrona20Layout.setHorizontalGroup(
            poltrona20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona20Layout.setVerticalGroup(
            poltrona20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona20);
        poltrona20.setBounds(190, 140, 30, 20);

        poltrona21.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona21Layout = new javax.swing.GroupLayout(poltrona21);
        poltrona21.setLayout(poltrona21Layout);
        poltrona21Layout.setHorizontalGroup(
            poltrona21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona21Layout.setVerticalGroup(
            poltrona21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona21);
        poltrona21.setBounds(20, 170, 30, 20);

        poltrona22.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona22Layout = new javax.swing.GroupLayout(poltrona22);
        poltrona22.setLayout(poltrona22Layout);
        poltrona22Layout.setHorizontalGroup(
            poltrona22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona22Layout.setVerticalGroup(
            poltrona22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona22);
        poltrona22.setBounds(60, 170, 30, 20);

        poltrona25.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona25Layout = new javax.swing.GroupLayout(poltrona25);
        poltrona25.setLayout(poltrona25Layout);
        poltrona25Layout.setHorizontalGroup(
            poltrona25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona25Layout.setVerticalGroup(
            poltrona25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona25);
        poltrona25.setBounds(20, 200, 30, 20);

        poltrona26.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona26Layout = new javax.swing.GroupLayout(poltrona26);
        poltrona26.setLayout(poltrona26Layout);
        poltrona26Layout.setHorizontalGroup(
            poltrona26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona26Layout.setVerticalGroup(
            poltrona26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona26);
        poltrona26.setBounds(60, 200, 30, 20);

        poltrona29.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona29Layout = new javax.swing.GroupLayout(poltrona29);
        poltrona29.setLayout(poltrona29Layout);
        poltrona29Layout.setHorizontalGroup(
            poltrona29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona29Layout.setVerticalGroup(
            poltrona29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona29);
        poltrona29.setBounds(20, 230, 30, 20);

        poltrona30.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona30Layout = new javax.swing.GroupLayout(poltrona30);
        poltrona30.setLayout(poltrona30Layout);
        poltrona30Layout.setHorizontalGroup(
            poltrona30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona30Layout.setVerticalGroup(
            poltrona30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona30);
        poltrona30.setBounds(60, 230, 30, 20);

        poltrona33.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona33Layout = new javax.swing.GroupLayout(poltrona33);
        poltrona33.setLayout(poltrona33Layout);
        poltrona33Layout.setHorizontalGroup(
            poltrona33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona33Layout.setVerticalGroup(
            poltrona33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona33);
        poltrona33.setBounds(20, 260, 30, 20);

        poltrona34.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona34Layout = new javax.swing.GroupLayout(poltrona34);
        poltrona34.setLayout(poltrona34Layout);
        poltrona34Layout.setHorizontalGroup(
            poltrona34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona34Layout.setVerticalGroup(
            poltrona34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona34);
        poltrona34.setBounds(60, 260, 30, 20);

        poltrona37.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona37Layout = new javax.swing.GroupLayout(poltrona37);
        poltrona37.setLayout(poltrona37Layout);
        poltrona37Layout.setHorizontalGroup(
            poltrona37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona37Layout.setVerticalGroup(
            poltrona37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona37);
        poltrona37.setBounds(20, 290, 30, 20);

        poltrona38.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona38Layout = new javax.swing.GroupLayout(poltrona38);
        poltrona38.setLayout(poltrona38Layout);
        poltrona38Layout.setHorizontalGroup(
            poltrona38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona38Layout.setVerticalGroup(
            poltrona38Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona38);
        poltrona38.setBounds(60, 290, 30, 20);

        poltrona39.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona39Layout = new javax.swing.GroupLayout(poltrona39);
        poltrona39.setLayout(poltrona39Layout);
        poltrona39Layout.setHorizontalGroup(
            poltrona39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona39Layout.setVerticalGroup(
            poltrona39Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona39);
        poltrona39.setBounds(150, 290, 30, 20);

        poltrona35.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona35Layout = new javax.swing.GroupLayout(poltrona35);
        poltrona35.setLayout(poltrona35Layout);
        poltrona35Layout.setHorizontalGroup(
            poltrona35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona35Layout.setVerticalGroup(
            poltrona35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona35);
        poltrona35.setBounds(150, 260, 30, 20);

        poltrona31.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona31Layout = new javax.swing.GroupLayout(poltrona31);
        poltrona31.setLayout(poltrona31Layout);
        poltrona31Layout.setHorizontalGroup(
            poltrona31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona31Layout.setVerticalGroup(
            poltrona31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona31);
        poltrona31.setBounds(150, 230, 30, 20);

        poltrona27.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona27Layout = new javax.swing.GroupLayout(poltrona27);
        poltrona27.setLayout(poltrona27Layout);
        poltrona27Layout.setHorizontalGroup(
            poltrona27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona27Layout.setVerticalGroup(
            poltrona27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona27);
        poltrona27.setBounds(150, 200, 30, 20);

        poltrona23.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona23Layout = new javax.swing.GroupLayout(poltrona23);
        poltrona23.setLayout(poltrona23Layout);
        poltrona23Layout.setHorizontalGroup(
            poltrona23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona23Layout.setVerticalGroup(
            poltrona23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona23);
        poltrona23.setBounds(150, 170, 30, 20);

        poltrona24.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona24Layout = new javax.swing.GroupLayout(poltrona24);
        poltrona24.setLayout(poltrona24Layout);
        poltrona24Layout.setHorizontalGroup(
            poltrona24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona24Layout.setVerticalGroup(
            poltrona24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona24);
        poltrona24.setBounds(190, 170, 30, 20);

        poltrona28.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona28Layout = new javax.swing.GroupLayout(poltrona28);
        poltrona28.setLayout(poltrona28Layout);
        poltrona28Layout.setHorizontalGroup(
            poltrona28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona28Layout.setVerticalGroup(
            poltrona28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona28);
        poltrona28.setBounds(190, 200, 30, 20);

        poltrona32.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona32Layout = new javax.swing.GroupLayout(poltrona32);
        poltrona32.setLayout(poltrona32Layout);
        poltrona32Layout.setHorizontalGroup(
            poltrona32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona32Layout.setVerticalGroup(
            poltrona32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona32);
        poltrona32.setBounds(190, 230, 30, 20);

        poltrona36.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona36Layout = new javax.swing.GroupLayout(poltrona36);
        poltrona36.setLayout(poltrona36Layout);
        poltrona36Layout.setHorizontalGroup(
            poltrona36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona36Layout.setVerticalGroup(
            poltrona36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona36);
        poltrona36.setBounds(190, 260, 30, 20);

        poltrona40.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona40Layout = new javax.swing.GroupLayout(poltrona40);
        poltrona40.setLayout(poltrona40Layout);
        poltrona40Layout.setHorizontalGroup(
            poltrona40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona40Layout.setVerticalGroup(
            poltrona40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona40);
        poltrona40.setBounds(190, 290, 30, 20);

        poltrona41.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona41Layout = new javax.swing.GroupLayout(poltrona41);
        poltrona41.setLayout(poltrona41Layout);
        poltrona41Layout.setHorizontalGroup(
            poltrona41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona41Layout.setVerticalGroup(
            poltrona41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona41);
        poltrona41.setBounds(20, 320, 30, 20);

        poltrona42.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona42Layout = new javax.swing.GroupLayout(poltrona42);
        poltrona42.setLayout(poltrona42Layout);
        poltrona42Layout.setHorizontalGroup(
            poltrona42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona42Layout.setVerticalGroup(
            poltrona42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona42);
        poltrona42.setBounds(60, 320, 30, 20);

        poltrona45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona45Layout = new javax.swing.GroupLayout(poltrona45);
        poltrona45.setLayout(poltrona45Layout);
        poltrona45Layout.setHorizontalGroup(
            poltrona45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona45Layout.setVerticalGroup(
            poltrona45Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona45);
        poltrona45.setBounds(20, 350, 30, 20);

        poltrona46.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona46Layout = new javax.swing.GroupLayout(poltrona46);
        poltrona46.setLayout(poltrona46Layout);
        poltrona46Layout.setHorizontalGroup(
            poltrona46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona46Layout.setVerticalGroup(
            poltrona46Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona46);
        poltrona46.setBounds(60, 350, 30, 20);

        poltrona43.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona43Layout = new javax.swing.GroupLayout(poltrona43);
        poltrona43.setLayout(poltrona43Layout);
        poltrona43Layout.setHorizontalGroup(
            poltrona43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona43Layout.setVerticalGroup(
            poltrona43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona43);
        poltrona43.setBounds(150, 320, 30, 20);

        poltrona44.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona44Layout = new javax.swing.GroupLayout(poltrona44);
        poltrona44.setLayout(poltrona44Layout);
        poltrona44Layout.setHorizontalGroup(
            poltrona44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona44Layout.setVerticalGroup(
            poltrona44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona44);
        poltrona44.setBounds(190, 320, 30, 20);

        poltrona47.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona47Layout = new javax.swing.GroupLayout(poltrona47);
        poltrona47.setLayout(poltrona47Layout);
        poltrona47Layout.setHorizontalGroup(
            poltrona47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona47Layout.setVerticalGroup(
            poltrona47Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona47);
        poltrona47.setBounds(150, 350, 30, 20);

        poltrona48.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout poltrona48Layout = new javax.swing.GroupLayout(poltrona48);
        poltrona48.setLayout(poltrona48Layout);
        poltrona48Layout.setHorizontalGroup(
            poltrona48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );
        poltrona48Layout.setVerticalGroup(
            poltrona48Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );

        jPanel1.add(poltrona48);
        poltrona48.setBounds(190, 350, 30, 20);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(lblOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29)
                                .addComponent(lblDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(46, 46, 46)
                                .addComponent(lblRota, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(46, 46, 46)
                                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(31, 31, 31)
                                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(lblOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(lblDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(lblRota, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnArquivo.setText("Administrator");

        btnLogin.setSelected(true);
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnArquivo.add(btnLogin);

        btnSair.setSelected(true);
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        btnArquivo.add(btnSair);

        jMenuBar1.add(btnArquivo);

        jMenu3.setText("Compras");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("Comprar Passagem");
        jRadioButtonMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem2);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("Retirar Passagem");
        jRadioButtonMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jRadioButtonMenuItem3);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Sobre");
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Integrantes");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jRadioButtonMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        new TelaVisualizacaoDados();
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        TelaInicial inicial = new TelaInicial();
        inicial.setLocationRelativeTo(null);
        inicial.setVisible(true);

        frmMenu tamanho = new frmMenu();
        tamanho.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void jRadioButtonMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem2ActionPerformed
        TelaCompra compra = new TelaCompra();
        compra.setLocationRelativeTo(null);
        compra.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem2ActionPerformed

    private void jRadioButtonMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem3ActionPerformed
        TelaRetiraPassagem retira = new TelaRetiraPassagem();
        retira.setLocationRelativeTo(null);
        retira.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem3ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        Integrantes integrantes = new Integrantes();
        integrantes.setLocationRelativeTo(null);
        integrantes.setVisible(true);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed

   }//GEN-LAST:event_jMenu4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TelaConfirmacao().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButtonMenuItem btnLogin;
    private javax.swing.JButton btnOK;
    private javax.swing.JRadioButtonMenuItem btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblOrigem;
    private javax.swing.JLabel lblRota;
    private javax.swing.JPanel poltrona1;
    private javax.swing.JPanel poltrona10;
    private javax.swing.JPanel poltrona11;
    private javax.swing.JPanel poltrona12;
    private javax.swing.JPanel poltrona13;
    private javax.swing.JPanel poltrona14;
    private javax.swing.JPanel poltrona15;
    private javax.swing.JPanel poltrona16;
    private javax.swing.JPanel poltrona17;
    private javax.swing.JPanel poltrona18;
    private javax.swing.JPanel poltrona19;
    private javax.swing.JPanel poltrona2;
    private javax.swing.JPanel poltrona20;
    private javax.swing.JPanel poltrona21;
    private javax.swing.JPanel poltrona22;
    private javax.swing.JPanel poltrona23;
    private javax.swing.JPanel poltrona24;
    private javax.swing.JPanel poltrona25;
    private javax.swing.JPanel poltrona26;
    private javax.swing.JPanel poltrona27;
    private javax.swing.JPanel poltrona28;
    private javax.swing.JPanel poltrona29;
    private javax.swing.JPanel poltrona3;
    private javax.swing.JPanel poltrona30;
    private javax.swing.JPanel poltrona31;
    private javax.swing.JPanel poltrona32;
    private javax.swing.JPanel poltrona33;
    private javax.swing.JPanel poltrona34;
    private javax.swing.JPanel poltrona35;
    private javax.swing.JPanel poltrona36;
    private javax.swing.JPanel poltrona37;
    private javax.swing.JPanel poltrona38;
    private javax.swing.JPanel poltrona39;
    private javax.swing.JPanel poltrona4;
    private javax.swing.JPanel poltrona40;
    private javax.swing.JPanel poltrona41;
    private javax.swing.JPanel poltrona42;
    private javax.swing.JPanel poltrona43;
    private javax.swing.JPanel poltrona44;
    private javax.swing.JPanel poltrona45;
    private javax.swing.JPanel poltrona46;
    private javax.swing.JPanel poltrona47;
    private javax.swing.JPanel poltrona48;
    private javax.swing.JPanel poltrona5;
    private javax.swing.JPanel poltrona6;
    private javax.swing.JPanel poltrona7;
    private javax.swing.JPanel poltrona8;
    private javax.swing.JPanel poltrona9;
    // End of variables declaration//GEN-END:variables
}
